# Generated by Django 6.0.8 on 2026-09-01 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Locations are deactivated, never deleted. Ledger entries reference them with PROTECT, so a delete would fail anyway.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_location',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LocationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='stock.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_location_assignment',
                'indexes': [models.Index(fields=['user'], name='assignment_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'location'), name='location_assignment_unique')],
            },
        ),
    ]
