# Generated by Django 6.0.8 on 2026-09-01 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment')], max_length=16)),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='stock.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.location')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_recorded', to=settings.AUTH_USER_MODEL)),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='stock.location')),
            ],
            options={
                'db_table': 'stock_movement',
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Signed. Negative removes stock.')),
                ('occurred_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='catalog.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='stock.location')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='stock.stockmovement')),
            ],
            options={
                'db_table': 'stock_ledger_entry',
            },
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', '-recorded_at'], name='movement_item_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-recorded_at'], name='movement_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('destination_location__isnull', False), ('kind', 'TRANSFER'), ('location__isnull', True), ('source_location__isnull', False), models.Q(('source_location', models.F('destination_location')), _negated=True)), models.Q(models.Q(('kind', 'TRANSFER'), _negated=True), ('destination_location__isnull', True), ('location__isnull', False), ('source_location__isnull', True)), _connector='OR'), name='movement_shape_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'ADJUSTMENT'), _negated=True), models.Q(('reason__isnull', False), models.Q(('reason__regex', '^\\s*$'), _negated=True)), _connector='OR'), name='movement_adjustment_needs_reason'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='movement_quantity_non_zero'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['item', 'location'], name='ledger_item_location_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['occurred_at'], name='ledger_occurred_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='ledger_delta_non_zero'),
        ),
    ]
