# Generated by Django 6.0.8 on 2026-09-03 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_timeline_immutability'),
        ('stock', '0003_immutability_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('reorder_level', models.IntegerField(help_text="The threshold at the time of dismissal, not the item's current one.")),
                ('cleared_at', models.DateTimeField(blank=True, help_text='Set when stock recovered above the reorder level.', null=True)),
                ('dismissed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts_dismissed', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='low_stock_dismissals', to='catalog.item')),
            ],
            options={
                'db_table': 'stock_low_stock_dismissal',
                'ordering': ['-dismissed_at'],
                'indexes': [models.Index(condition=models.Q(('cleared_at__isnull', True)), fields=['item'], name='active_dismissal_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cleared_at__isnull', True)), fields=('item',), name='one_active_dismissal_per_item')],
            },
        ),
    ]
