# Generated by Django 6.0.8 on 2026-09-01 05:10

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'catalog_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_of_measure', models.CharField(default='EA', max_length=16)),
                ('reorder_level', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False, help_text='Archived items drop out of day-to-day lists and reject new movements, but keep their full history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category')),
            ],
            options={
                'db_table': 'catalog_item',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('sku'), name='item_sku_ci_unique'), models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='item_reorder_level_non_negative')],
            },
        ),
    ]
