# Generated by Django 6.0.8 on 2026-09-02 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_trigram_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('FIELD_CHANGE', 'Field changed'), ('NOTE', 'Note'), ('ARCHIVED', 'Archived'), ('RESTORED', 'Restored')], max_length=16)),
                ('field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('note_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='timeline', to='catalog.item')),
            ],
            options={
                'db_table': 'catalog_item_timeline_event',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['item', '-created_at'], name='timeline_item_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'FIELD_CHANGE'), ('field_name__isnull', False), ('note_body__isnull', True)), models.Q(('event_type', 'NOTE'), ('field_name__isnull', True), ('note_body__isnull', False)), ('event_type__in', ['CREATED', 'ARCHIVED', 'RESTORED']), _connector='OR'), name='timeline_event_shape_valid')],
            },
        ),
    ]
