# Generated by Django 6.0.8 on 2026-09-03 12:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    """Swap Category.name's case-sensitive unique index for a case-insensitive
    one.

    The two operations have to happen in this order: AlterField drops the old
    index first, so there is never a moment where both exist and a legitimate
    recapitalisation is blocked by the one on its way out.

    This will fail on any database that already holds two categories differing
    only in case -- which is the correct outcome, since the whole point is that
    such a pair should never have existed. Ours has none.
    """


    dependencies = [
        ('catalog', '0004_timeline_immutability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='category_name_unique_ci'),
        ),
    ]
