# Generated by Django 6.0.8 on 2026-09-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_name_category_category_name_unique_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
